name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Git Submodules
      run: git submodule update --init --recursive 
    - name: meson_init
      run: pip install meson ninja
    - name: meson_setup
      run:
        meson setup builddir
    - name: meson_compile
      run: meson compile -C builddir

